#!/bin/sh

###
# watchnet
#
# Monitors a network interface connection, notifies changes to the user
# and reconnects the interface when possible.
#
#  (C) 2013-2017 Jordi Pujol <jordipujolp@gmail.com>
# GNU General Public License v3.0
#
# Homepage:
# https://github.com/jordi-pujol/watchnet
#
# Debian repository:
# deb [arch=amd64,i386] http://livenet.ddns.net/ftp/debian/ sid main
# deb-src http://livenet.ddns.net/ftp/debian/ sid main
###
# watchnet-ifupdown
# This is an script to select a mapping in /etc/network/interfaces.
# Calls guessnet-ifupdown and after submits the watchnet daemon.
#
# Usage:
# mapping iface0
#     script /usr/sbin/watchnet-ifupdown
###

iface="${1:-}"
if [ -z "${iface}" ] || \
[ ! -L "/sys/class/net/${iface}" ]; then
	echo "Error: network device ${iface} does not exist." >&2
	exit 1
fi

if [ -x /usr/sbin/guessnet-ifupdown ]; then
	/usr/sbin/guessnet-ifupdown "${@}" || exit "${?}"
else
	awk -v iface="${iface}" \
	'$1 == "iface" && $2 ~ "^" iface "([-]|$)" {print $2; rc=-1; exit}
	END{exit rc+1}' /etc/network/interfaces || \
		exit 1
fi

echo "watchnet: watching network interface ${iface}." >&2
setsid setsid /usr/sbin/watchnetd "${@}" > /dev/null 2>&1
:
