#!/bin/sh

###
# Live never ending Tale
#
# live-net-initramfs script
#
#  (C) 2009-2016 Jordi Pujol <jordipujolp@gmail.com>
# License:   GPLv2
#
# Live never ending Tale Project Homepage:
# http://livenet.selfip.com
###

iface="${1:-}"
if [ -z "${iface}" ] || \
[ ! -L "/sys/class/net/${iface}" ]; then
	echo "Error: network device ${iface} does not exist." >&2
	exit 1
fi

if [ -x /usr/sbin/guessnet-ifupdown ]; then
	/usr/sbin/guessnet-ifupdown "${@}" || exit "${?}"
else
	awk -v iface="${iface}" \
	'$1 == "iface" && $2 ~ "^" iface "([-]|$)" {print $2; rc=-1; exit}
	END{exit rc+1}' /etc/network/interfaces || \
		exit 1
fi

echo "watchnet: watching network interface ${iface}." >&2
setsid setsid /usr/sbin/watchnetd "${@}" > /dev/null 2>&1
:
